### ISSUE TITLE
[To-Do] 1.2.0 - Dependency management

### ISSUE THREAD

**Issue by notronaldmcdonald** [notronaldmcdonald/blinky#12]
### Main Point(s)
Write a shell script component to automatically install dependencies.
### Checklist
- [x] Write script.
- [x] Read `deps` array from PKGBUILD.
- [x] Install deps via pacman.
- [x] Enable use of the script from [script_main.rb](https://github.com/notronaldmcdonald/blinky/blob/stable/script_main.rb)

**Comment by notronaldmcdonald** [comment]
included feature: skip dependencies already installed (limit five)

**Comment by notronaldmcdonald** [comment]
now iterates over every dependency

**Comment by notronaldmcdonald** [comment]
completed: close with pr #14
